from collections.abc import Iterable, Iterator
from typing import Generic, TypeVar, overload

_T = TypeVar("_T")


class SortedList(Generic[_T]):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, iterable: Iterable[_T]) -> None: ...
    def add(self, value: _T) -> None: ...
    def discard(self, value: _T) -> None: ...
    def remove(self, value: _T) -> None: ...
    def bisect_right(self, value: _T) -> int: ...
    def pop(self, index: int = ...) -> _T: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __contains__(self, value: object) -> bool: ...

    @overload
    def __getitem__(self, index: int) -> _T: ...

    @overload
    def __getitem__(self, index: slice) -> list[_T]: ...
